### ISSUE TITLE
Option to generate C header file appears to not work in these builds

### ISSUE THREAD

**Issue by rod-chapman** [simonjwright/distributing-gcc#15]
I'm trying to use the -gnatceg option to generate a C header file from an Ada package specification.

GNAT UG says this should work, and it does work OK with GNAT Community 2019, GNAT Community 2020 and GNAT Pro 20.1.

With these builds - specifically GCC 12.1.0, 12.2.0 and 13.1.0 for Aarch64/macOS, the -gnatceg option does not appear to work. No .h file is generated.

Any idea what might be causing this?

**Comment by rod-chapman** [comment]
It also appears to fail using the gnat_native_12.1.2 package installed by Alire.

**Comment by simonjwright** [comment]
It seems it was never part of the FSF branch of the compiler.
