### ISSUE TITLE
Command Line Tools check

### ISSUE THREAD

**Issue by trashgod** [simonjwright/distributing-gcc#5]
Recent releases helpfully mention that "One of Xcode or the Command Line Tools is required." In addition to the verification checks mentioned, I found this `pkgutil` [example](https://stackoverflow.com/a/74363730/230513) helpful. Would it be useful to cite it?

**Comment by simonjwright** [comment]
Sorry for delay.

Not quite sure how that would be helpful?

I could add
> Xcode is an application, and can be obtained from the App Store under the Develop tab; the Command Line Tools (which are much smaller) can be installed by saying in a Terminal `xcode-select --install`.

**Comment by trashgod** [comment]
Simon: Thanks for looking at this; I defer entirely to you on any further action. I found it helpful in my understanding of Issue #1, as well as occassional regressions in Apple's later releases.
