### ISSUE TITLE
getting permission denied while running ./doinstall shell script

### ISSUE THREAD

**Issue by kiran-kumar011** [simonjwright/distributing-gcc#7]
rm -fr /opt/gcc-11.1.0/lib/gcc/x86_64-apple-darwin15/11.1.0/rts*
rm -fr /opt/gcc-11.1.0/lib/gcc/x86_64-apple-darwin15/11.1.0/adainclude /opt/gcc-11.1.0/lib/gcc/x86_64-apple-darwin15/11.1.0/adalib
mkdir -p /opt/gcc-11.1.0
mkdir: /opt/gcc-11.1.0: Permission denied
make: *** [mkdirs] Error 1

**Comment by simonjwright** [comment]
That package is released on [Sourceforge](https://sourceforge.net/projects/gnuada/files/GNAT_GCC%20Mac%20OS%20X/11.1.0/native/), not here!

That said, the README says

> **Install**
> Xcode is required.
> 
> Download the binary .pkg. It's not signed, so don't double-click on it; instead, right-click on it and Open. Accept the warning. You will be guided through the installation.

**Comment by simonjwright** [comment]
Also,
* see [this ticket](https://sourceforge.net/p/gnuada/bugs/20/) for why you might not want to use 11.1.0
* if you get a permissions problem like this, use `sudo`
