### ISSUE TITLE
need installation support on GNAT studio in M1 Mac

### ISSUE THREAD

**Issue by pkotbull** [simonjwright/distributing-gcc#8]
Hello @simonjwright ,

I have installed GNAT studio from [source forge v12.1.0](https://sourceforge.net/projects/gnuada/files/GNAT_GPL%20Mac%20OS%20X/2022-monterey/)
in m1 Mac , but unable to compile and run the ADA code. 
---error message ---
`gprbuild -d -P/Users/prathi/default.gpr /Users/prathi/src/main.adb
default.gpr:3:24: object directory "obj" not found
gprbuild: "/Users/prathi/default.gpr" processing failed
[2022-12-05 09:23:59] process exited with status 4, elapsed time: 01.52s
`
have installed Xcode and followed the steps as stated. 
system configs:
Xcode : v14.1
OS :Ventura-13.0.1
 
please provide steps to resolve installation issues.
<img width="1051" alt="Screenshot 2022-12-05 at 9 36 17 am" src="https://user-images.githubusercontent.com/119846991/205603810-7a1f088b-6248-4b2f-afe9-316eb869e7f1.png">

**Comment by simonjwright** [comment]
Include the line
```
for Create_Missing_Dirs use "true";
```
in your GPR file.

(you could say `gprbuild -p ...` to get the same effect, but putting it in the GPR file means you don't have to remember).
